use_frameworks!

platform :ios, '8.0'



target 'IMSDK_Example' do
  pod 'IMSDK', :path => '../'
  pod 'Protobuf', '3.11.4'
  pod 'CocoaAsyncSocket'
  pod 'ReactiveObjC'


  target 'IMSDK_Tests' do
    inherit! :search_paths

    
  end
end
